Repository googleapis/python-access-context-manager, pull requests merged in 2021-04, with the labels that each got.

#28 build: fix generate_protos session
  .gitignore
  noxfile.py
Labels: api: accesscontextmanager, automerge, cla: yes

#29 chore: prevent normalization of semver versioning
  setup.py
Labels: api: accesscontextmanager, cla: yes

#30 chore: update templates
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .pre-commit-config.yaml
  docs/_static/custom.css
  docs/conf.py
  renovate.json
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: full

#31 chore(revert): revert preventing normalization
  setup.py
Labels: api: accesscontextmanager, cla: yes
